
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.database_funcoes_DAO;

public class bd_DGV_GUI extends javax.swing.JFrame {
    
    public bd_DGV_GUI() {
        initComponents();
        
        try {
            database_funcoes_DAO.carregaProfessoresBD();
            database_funcoes_DAO.carregaChavesBD();
            database_funcoes_DAO.carregaItensBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoPrincipal = new javax.swing.JPanel();
        cadastroProf = new javax.swing.JPanel();
        profTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cadastroChave = new javax.swing.JPanel();
        chaveTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cadastroItem = new javax.swing.JPanel();
        itemTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        removerProf = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        profCBJ = new javax.swing.JComboBox();
        removerProf1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        chaveCBJ = new javax.swing.JComboBox();
        removerProf2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        itemCBJ = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Dados");
        setUndecorated(true);

        FundoPrincipal.setLayout(null);

        cadastroProf.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Professores"));

        jLabel1.setText("Nome do(a) Professor(a)");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroProfLayout = new javax.swing.GroupLayout(cadastroProf);
        cadastroProf.setLayout(cadastroProfLayout);
        cadastroProfLayout.setHorizontalGroup(
            cadastroProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroProfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroProfLayout.createSequentialGroup()
                        .addComponent(profTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(cadastroProfLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastroProfLayout.setVerticalGroup(
            cadastroProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroProfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(profTXT))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        FundoPrincipal.add(cadastroProf);
        cadastroProf.setBounds(10, 10, 310, 110);

        cadastroChave.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Chaves"));

        jLabel2.setText("Numeração da Chave");

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroChaveLayout = new javax.swing.GroupLayout(cadastroChave);
        cadastroChave.setLayout(cadastroChaveLayout);
        cadastroChaveLayout.setHorizontalGroup(
            cadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroChaveLayout.createSequentialGroup()
                        .addComponent(chaveTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(cadastroChaveLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastroChaveLayout.setVerticalGroup(
            cadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(chaveTXT))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        FundoPrincipal.add(cadastroChave);
        cadastroChave.setBounds(10, 130, 310, 110);

        cadastroItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Itens"));

        jLabel3.setText("Nome do Item");

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroItemLayout = new javax.swing.GroupLayout(cadastroItem);
        cadastroItem.setLayout(cadastroItemLayout);
        cadastroItemLayout.setHorizontalGroup(
            cadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroItemLayout.createSequentialGroup()
                        .addComponent(itemTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(cadastroItemLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastroItemLayout.setVerticalGroup(
            cadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(itemTXT))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        FundoPrincipal.add(cadastroItem);
        cadastroItem.setBounds(10, 250, 310, 110);

        removerProf.setBorder(javax.swing.BorderFactory.createTitledBorder("Remover Professores"));

        jLabel4.setText("Nome do(a) Professor(a)");

        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        profCBJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout removerProfLayout = new javax.swing.GroupLayout(removerProf);
        removerProf.setLayout(removerProfLayout);
        removerProfLayout.setHorizontalGroup(
            removerProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerProfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removerProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removerProfLayout.createSequentialGroup()
                        .addComponent(profCBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(removerProfLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        removerProfLayout.setVerticalGroup(
            removerProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerProfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removerProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(profCBJ))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        FundoPrincipal.add(removerProf);
        removerProf.setBounds(400, 10, 310, 110);

        removerProf1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remover Chaves"));

        jLabel5.setText("Numeração da Chave");

        jButton5.setText("Remover");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        chaveCBJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout removerProf1Layout = new javax.swing.GroupLayout(removerProf1);
        removerProf1.setLayout(removerProf1Layout);
        removerProf1Layout.setHorizontalGroup(
            removerProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerProf1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removerProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removerProf1Layout.createSequentialGroup()
                        .addComponent(chaveCBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(removerProf1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        removerProf1Layout.setVerticalGroup(
            removerProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerProf1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removerProf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(chaveCBJ))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        FundoPrincipal.add(removerProf1);
        removerProf1.setBounds(400, 130, 310, 110);

        removerProf2.setBorder(javax.swing.BorderFactory.createTitledBorder("Remover Itens"));

        jLabel6.setText("Nome do Item");

        jButton6.setText("Remover");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        itemCBJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout removerProf2Layout = new javax.swing.GroupLayout(removerProf2);
        removerProf2.setLayout(removerProf2Layout);
        removerProf2Layout.setHorizontalGroup(
            removerProf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerProf2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removerProf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removerProf2Layout.createSequentialGroup()
                        .addComponent(itemCBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(removerProf2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        removerProf2Layout.setVerticalGroup(
            removerProf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerProf2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removerProf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(itemCBJ))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        FundoPrincipal.add(removerProf2);
        removerProf2.setBounds(400, 250, 310, 110);

        jButton8.setText("Voltar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        FundoPrincipal.add(jButton8);
        jButton8.setBounds(570, 370, 140, 40);

        jLabel7.setText("@yasnikki - github");
        FundoPrincipal.add(jLabel7);
        jLabel7.setBounds(10, 464, 710, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(730, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        new home_DGV_GUI().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        model.database_funcoes_DAO.cadastraProf();
        try {
            database_funcoes_DAO.carregaProfessoresBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        model.database_funcoes_DAO.cadastraChave();
        try {
            database_funcoes_DAO.carregaChavesBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        model.database_funcoes_DAO.cadastraItem();
        try {
            database_funcoes_DAO.carregaItensBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        database_funcoes_DAO.removerProf();
        try {
            database_funcoes_DAO.carregaProfessoresBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        database_funcoes_DAO.removerChave();
        try {
            database_funcoes_DAO.carregaChavesBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        database_funcoes_DAO.removerItem();
        try {
            database_funcoes_DAO.carregaItensBD();
        } catch (SQLException ex) {
            Logger.getLogger(bd_DGV_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bd_DGV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bd_DGV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bd_DGV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bd_DGV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bd_DGV_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FundoPrincipal;
    private javax.swing.JPanel cadastroChave;
    private javax.swing.JPanel cadastroItem;
    private javax.swing.JPanel cadastroProf;
    public static javax.swing.JComboBox chaveCBJ;
    public static javax.swing.JTextField chaveTXT;
    public static javax.swing.JComboBox itemCBJ;
    public static javax.swing.JTextField itemTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JComboBox profCBJ;
    public static javax.swing.JTextField profTXT;
    private javax.swing.JPanel removerProf;
    private javax.swing.JPanel removerProf1;
    private javax.swing.JPanel removerProf2;
    // End of variables declaration//GEN-END:variables
}
